/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package basics;


import java.time.LocalDateTime;

public class Main {

    public static void main(String[] args) {
        // System.out.println(pluralize("rrrr", 3));
        flipNHeads(2);


    }

    public static String pluralize(String word, int num) {

        if (num == 0 || num > 1) {
            return word + "s";
        }
        return word;
    }

    public static void flipNHeads(int n){
        int headsCounter = 0;
        int totalCounter = 0;

        while (n != headsCounter){
            double randomNum = Math.random();
            if (randomNum > .5){
                headsCounter++;
                System.out.println("heads");

            } else {
                headsCounter =0;
                totalCounter++;
                System.out.println("tails");

            }

        }

        System.out.println("It took " + totalCounter + " flips to flip " + n + " heads in a row.");

    }

    public static void clock(){
        LocalDateTime now = LocalDateTime.now();


    }


}
