/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Path path = Paths.get("linter/gates.js");
        try {
            List<String> lines = Files.readAllLines(path);
            System.out.println(lines.size());

        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }


    }
