/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testrollMethod(){
        int array[] = Library.roll(4);
        assertEquals(4,array.length);

    }

    @Test public void testcontainsDuplicatesFalseMethod(){
        int[] array = {1, 5, 2, 3};
        assertFalse("no duplicate",Library.containsDuplicates(array));

    }

    @Test public void testcontainsDuplicatesTrueMethod(){
        int[] array = {1, 2, 2, 3};
        assertTrue("duplicate",Library.containsDuplicates(array));

    }

    @Test public void testcalculateAverage(){
        int[] array = {1, 1, 1, 1};
        float average;
        average = Library.calculateAverage(array);
        assertEquals(1.0,average,1.0);
    }

    @Test public void testcalculateAverageOfTwoArrays() {
        int[][] array = {{1, 1, 1, 1}, {2, 2, 2, 2}, {3, 3, 3, 3}};
        float average = Library.calculateAverageOfTwoArrays(array);
        assertEquals(1.0, average, 1.0);
    }

    @Test public void testanalyzeWeather() {
        int[][] array = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String output = Library.AnalyzingWeatherData(array);
        assertEquals("High: 72\nLow: 51\nNever saw temperature: 63\nNever saw temperature: 67\nNever saw temperature: 68\nNever saw temperature: 69\n", output);
    }


    @Test public void tally() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        Library library = new Library();
        assertEquals("Bush received the most votes!", library.tally(votes));
    }
}


