/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {

        Restaurant restaurant = new Restaurant("mmm",5,"$");
        Review review = new Review("DDD",3);
//        restaurant.toString();
        review.toString();

    }
}
