/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    Restaurant restaurant;
    Review review;
    @Before
    public void init() {
        restaurant = new Restaurant("Irbid", 4, "$");
        review = new Review( "Ahmad", 5);
    }

    @Test public void restaurantToStringTest() {
        assertEquals("Restaurant{name='Irbid', rating=4, price_category='$'}", restaurant.toString());
    }

    @Test public void reveiewToStringTest() {
        assertEquals("Review{author='Ahmad', rating='5'}", review.toString());
    }
}
